---
- hosts: localhost
  connection: local
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: argocd
        api_version: v1
        kind: Namespace
        state: present

    - name: Install ArgoCD
      command: "kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml"
    - name: Obtain password
      register: password
      command:  "kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d > password.txt"
    - debug:
        var: password.stdout_lines  