---
- hosts: localhost
  connection: local
  tasks:
    - name: Port Forward Service
      register: port
      command: "kubectl port-forward svc/terraform-monitoring 5000"
    - debug:
        var: port.stdout_lines